apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  selector:
    matchLabels:
      app: api-server
  replicas: 1
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: lamooon/back
        ports:
        - containerPort: 5050
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_DATABASE
          value: blog
        - name: MYSQL_ROOT_PASSWORD
          value: root1234
