apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql
    tier: database
spec:
  resources:
    requests:
      storage: 256Mi
  accessModes:
    - ReadWriteOnce
